[Compiler] Fixes for cross-compilation of Torq compiler
This commit includes multiple fixes for the cross compilation of the compiler for Arm64:

* fixing ambiguity errors like:
```
compiler/torq/Conversions/LinalgToTorqHL/ClampPattern.cpp:316:69: error: call of overloaded 'interleave(<brace-enclosed initializer list>, <brace-enclosed initializer list>)' is ambiguous
```
* adding missing dependencies,
* adjusting asserts.

---------

Signed-off-by: Maciej Torhan <mtorhan@antmicro.com>
Co-authored-by: Maciej Torhan <mtorhan@antmicro.com>